name: github-label-sync

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/github-label-sync.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: r7kamura/github-label-sync-action@061649dd3b80eb5bafad0316466f72962e62c300 # v0.1.0
        with:
          source_path: labels-keepachangelog.yml
          source_repository: r7kamura/github-label-presets
